import { calculateRate } from './utils';

const data = [
    {
        id: 'b',
        title: 'Grundleistungen',
        records: [
            {
                id: 'i',
                title: 'Allgemeine Beratungen und Untersuchungen',
                records: [
                    {
                        number: 1,
                        title: 'Beratung auch mittels Fernsprecher',
                        points: 80,
                        simple_unit_rate: calculateRate(80),
                        max_unit_rate: '?',
                    },
                    {
                        number: 2,
                        title: 'Ausstellung von Wiederholungsrezepten und/oder Überweisungen und/oder Übermittlung von Befunden oder ärztlichen Anordnungen auch mittels Fernsprecher durch die Arzthelferin und/oder Messung von Körperzuständen (z. B. Blutdruck, Temperatur) ohne Beratung, bei einer Inanspruchnahme des Arztes',
                        points: 30,
                        simple_unit_rate: calculateRate(30),
                        max_unit_rate: '?',
                    },
                    {
                        number: 3,
                        title: 'Eingehende, das gewöhnliche Maß übersteigende Beratung auch mittels Fernsprecher',
                        points: 150,
                        simple_unit_rate: calculateRate(150),
                        max_unit_rate: '?',
                    },
                    {
                        number: 4,
                        title: 'Erhebung der Fremdanamnese über einen Kranken und/oder Unterweisung und Führung der Bezugsperson(en) im Zusammenhang mit der Behandlung eines Kranken',
                        points: 220,
                        simple_unit_rate: calculateRate(220),
                        max_unit_rate: '?',
                    },
                    {
                        number: 5,
                        title: 'Symptombezogene Untersuchung',
                        points: 80,
                        simple_unit_rate: calculateRate(80),
                        max_unit_rate: '?',
                    },
                    {
                        number: 6,
                        title: 'Vollständige körperliche Untersuchung mindestens eines der folgenden Organsysteme: alle Augenabschnitte, der gesamte HNO-Bereich, das stomatognathe System, die Nieren und ableitenden Harnwege (bei Männern auch gegebenenfalls einschließlich der männlichen Geschlechtsorgane) oder Untersuchung zur Erhebung eines vollständigen Gefäßstatus gegebenenfalls einschließlich Dokumentation',
                        points: 100,
                        simple_unit_rate: calculateRate(100),
                        max_unit_rate: '?',
                    },
                    {
                        number: 7,
                        title: 'Vollständige körperliche Untersuchung mindestens eines der folgenden Organsysteme: das gesamte Hautorgan, die Stütz- und Bewegungsorgane, alle Brustorgane, alle Bauchorgane, der gesamte weibliche Genitaltrakt (gegebenenfalls einschließlich Nieren und ableitende Harnwege) gegebenenfalls einschließlich Dokumentation',
                        points: 160,
                        simple_unit_rate: calculateRate(160),
                        max_unit_rate: '?',
                    },
                    {
                        number: 8,
                        title: 'Untersuchung zur Erhebung des Ganzkörperstatus, gegebenenfalls einschließlich Dokumentation',
                        points: 260,
                        simple_unit_rate: calculateRate(260),
                        max_unit_rate: '?',
                    },
                    {
                        number: 11,
                        title: 'Digitaluntersuchung des Mastdarms und/oder der Prostata',
                        points: 60,
                        simple_unit_rate: calculateRate(60),
                        max_unit_rate: '?',
                    },
                    {
                        number: 15,
                        title: 'Einleitung und Koordination flankierender therapeutischer und sozialer Maßnahmen während der kontinuierlichen ambulanten Betreuung eines chronisch Kranken',
                        points: 300,
                        simple_unit_rate: calculateRate(300),
                        max_unit_rate: '?',
                    },
                ],
            },
            {
                id: 'ii',
                title: 'Zuschläge zu Beratungen und Untersuchungen nach den Nummern 1, 3, 4, 5, 6, 7 oder 8',
                records: [],
            },
            {
                id: 'iii',
                title: 'Spezielle Beratungen und Untersuchungen',
                records: [],
            },
            {
                id: 'iv',
                title: 'Visiten, Konsiliartätigkeit, Besuche, Assistenz',
                records: [],
            },
            {
                id: 'v',
                title: 'Zuschläge zu den Leistungen nach den Nummern 45 bis 62',
                records: [],
            },
            {
                id: 'vi',
                title: 'Berichte, Briefe',
                records: [],
            },
            {
                id: 'vii',
                title: 'Todesfeststellung',
                records: [],
            },
        ],
    },
    {
        id: 'c',
        title: 'Sonderleistungen',
        records: [
            {
                id: 'i',
                title: 'Anlegen von Verbänden',
                records: [],
            },
            {
                id: 'ii',
                title: 'Blutentnahmen, Injektionen, Infiltrationen, Infusionen, Transfusionen, Implantation, Abstrichentnahmen',
                records: [],
            },
            {
                id: 'iii',
                title: 'Punktionen',
                records: [],
            },
            {
                id: 'iv',
                title: 'Kontrastmitteleinbringungen',
                records: [],
            },
            {
                id: 'v',
                title: 'Impfungen und Testungen',
                records: [],
            },
            {
                id: 'vi',
                title: 'Sonographische Leistungen',
                records: [],
            },
            {
                id: 'vii',
                title: 'Intensivmedizinische und sonstige Leistungen',
                records: [],
            },
            {
                id: 'viii',
                title: 'Zuschläge zu ambulanten Operations- und Anästhesieleistungen',
                records: [],
            },
        ],
    },
    {
        id: 'd',
        title: 'Anästhesieleistungen',
        records: [
            {
                number: 450,
                title: 'Rauschnarkose auch mit Lachgas',
                points: 76,
                simple_unit_rate: calculateRate(76),
                max_unit_rate: '?',
            },
            {
                number: 451,
                title: 'Intravenöse Kurznarkose',
                points: 121,
                simple_unit_rate: calculateRate(121),
                max_unit_rate: '?',
            },
            {
                number: 452,
                title: 'Intravenöse Narkose (mehrmalige Verabreichung des Narkotikums)',
                points: 190,
                simple_unit_rate: calculateRate(190),
                max_unit_rate: '?',
            },
            {
                number: 453,
                title: 'Vollnarkose',
                points: 210,
                simple_unit_rate: calculateRate(210),
                max_unit_rate: '?',
            },
            {
                number: 460,
                title: 'Kombinationsnarkose mit Maske, Gerät auch Insufflationsnarkose , bis zu einer Stunde',
                points: 404,
                simple_unit_rate: calculateRate(404),
                max_unit_rate: '?',
            },
            {
                number: 461,
                title: 'Kombinationsnarkose mit Maske, Gerät auch Insufflationsnarkose , jede weitere angefangene halbe Stunde',
                points: 202,
                simple_unit_rate: calculateRate(202),
                max_unit_rate: '?',
            },
            {
                number: 462,
                title: 'Kombinationsnarkose mit endotrachealer Intubation, bis zu einer Stunde',
                points: 510,
                simple_unit_rate: calculateRate(510),
                max_unit_rate: '?',
            },
            {
                number: 463,
                title: 'Kombinationsnarkose mit endotrachealer Intubation, jede weitere angefangene halbe Stunde',
                points: 348,
                simple_unit_rate: calculateRate(348),
                max_unit_rate: '?',
            },
            {
                number: 469,
                title: 'Kaudalanästhesie',
                points: 250,
                simple_unit_rate: calculateRate(250),
                max_unit_rate: '?',
            },
            {
                number: 470,
                title: 'Einleitung und Überwachung einer einzeitigen subarachnoidalen Spinalanästhesie (Lumbalanästhesie) oder einzeitigen periduralen (epiduralen) Anästhesie, bis zu einer Stunde Dauer',
                points: 400,
                simple_unit_rate: calculateRate(400),
                max_unit_rate: '?',
            },
            {
                number: 471,
                title: 'Einleitung und Überwachung einer einzeitigen subarachnoidalen Spinalanästhesie (Lumbalanästhesie) oder einzeitigen periduralen (epiduralen) Anästhesie, bis zu zwei Stunden Dauer',
                points: 600,
                simple_unit_rate: calculateRate(600),
                max_unit_rate: '?',
            },
            {
                number: 472,
                title: 'Einleitung und Überwachung einer einzeitigen subarachnoidalen Spinalanästhesie (Lumbalanästhesie) oder einzeitigen periduralen (epiduralen) Anästhesie, bei mehr als zwei Stunden Dauer',
                points: 800,
                simple_unit_rate: calculateRate(800),
                max_unit_rate: '?',
            },
            {
                number: 473,
                title: 'Einleitung und Überwachung einer kontinuierlichen subarachnoidalen Spinalanästhesie (Lumbalanästhesie) oder periduralen (epiduralen) Anästhesie mit Katheter, bis zu fünf Stunden Dauer',
                points: 600,
                simple_unit_rate: calculateRate(600),
                max_unit_rate: '?',
            },
            {
                number: 474,
                title: 'Einleitung und Überwachung einer kontinuierlichen subarachnoidalen Spinalanästhesie (Lumbalanästhesie) oder periduralen (epiduralen) Anästhesie mit Katheter, bei mehr als fünf Stunden Dauer',
                points: 900,
                simple_unit_rate: calculateRate(900),
                max_unit_rate: '?',
            },
            {
                number: 475,
                title: 'Überwachung einer kontinuierlichen subarachnoidalen Spinalanästhesie (Lumbalanästhesie) oder periduralen (epiduralen) Anästhesie mit Katheter, zusätzlich zur Leistung nach Nummer 474 für den zweiten und jeden weiteren Tag, je Tag',
                points: 450,
                simple_unit_rate: calculateRate(450),
                max_unit_rate: '?',
            },
            {
                number: 476,
                title: 'Einleitung und Überwachung einer supraklavikulären oder axillären Armplexus- oder Paravertebralanästhesie, bis zu einer Stunde Dauer',
                points: 380,
                simple_unit_rate: calculateRate(380),
                max_unit_rate: '?',
            },
            {
                number: 477,
                title: 'Überwachung einer supraklavikulären oder axillären Armplexus- oder Paravertebralanästhesie, jede weitere angefangene Stunde',
                points: 190,
                simple_unit_rate: calculateRate(190),
                max_unit_rate: '?',
            },
            {
                number: 478,
                title: 'Intravenöse Anästhesie einer Extremität, bis zu einer Stunde Dauer',
                points: 230,
                simple_unit_rate: calculateRate(230),
                max_unit_rate: '?',
            },
            {
                number: 479,
                title: 'Intravenöse Anästhesie einer Extremität, jede weitere angefangene Stunde',
                points: 115,
                simple_unit_rate: calculateRate(115),
                max_unit_rate: '?',
            },
            {
                number: 480,
                title: 'Kontrollierte Blutdrucksenkung während der Narkose',
                points: 222,
                simple_unit_rate: calculateRate(222),
                max_unit_rate: '?',
            },
            {
                number: 481,
                title: 'Kontrollierte Hypothermie während der Narkose',
                points: 475,
                simple_unit_rate: calculateRate(475),
                max_unit_rate: '?',
            },
            {
                number: 483,
                title: 'Lokalanästhesie der tieferen Nasenabschnitte gegebenenfalls einschließlich des Rachens, auch beidseitig',
                points: 46,
                simple_unit_rate: calculateRate(46),
                max_unit_rate: '?',
            },
            {
                number: 484,
                title: 'Lokalanästhesie des Kehlkopfes',
                points: 46,
                simple_unit_rate: calculateRate(46),
                max_unit_rate: '?',
            },
            {
                number: 485,
                title: 'Lokalanästhesie des Trommelfells und/oder der Paukenhöhle',
                points: 46,
                simple_unit_rate: calculateRate(46),
                max_unit_rate: '?',
            },
            {
                number: 488,
                title: 'Lokalanästhesie der Harnröhre und/oder Harnblase',
                points: 46,
                simple_unit_rate: calculateRate(46),
                max_unit_rate: '?',
            },
            {
                number: 489,
                title: 'Lokalanästhesie des Bronchialgebietes gegebenenfalls einschließlich des Kehlkopfes und des Rachens',
                points: 145,
                simple_unit_rate: calculateRate(145),
                max_unit_rate: '?',
            },
            {
                number: 490,
                title: 'Infiltrationsanästhesie kleiner Bezirke',
                points: 61,
                simple_unit_rate: calculateRate(61),
                max_unit_rate: '?',
            },
            {
                number: 491,
                title: 'Infiltrationsanästhesie großer Bezirke auch Parazervikalanästhesie',
                points: 121,
                simple_unit_rate: calculateRate(121),
                max_unit_rate: '?',
            },
            {
                number: 493,
                title: 'Leitungsanästhesie, perineural auch nach Oberst',
                points: 61,
                simple_unit_rate: calculateRate(61),
                max_unit_rate: '?',
            },
            {
                number: 494,
                title: 'Leitungsanästhesie, endoneural auch Pudendusanästhesie',
                points: 121,
                simple_unit_rate: calculateRate(121),
                max_unit_rate: '?',
            },
            {
                number: 495,
                title: 'Leitungsanästhesie, retrobulbär',
                points: 121,
                simple_unit_rate: calculateRate(121),
                max_unit_rate: '?',
            },
            {
                number: 497,
                title: 'Blockade des Truncus sympathicus (lumbaler Grenzstrang oder Ganglion stellatum) mittels Anästhetika',
                points: 220,
                simple_unit_rate: calculateRate(220),
                max_unit_rate: '?',
            },
            {
                number: 498,
                title: 'Blockade des Truncus sympathicus (thorakaler Granzstrang oder Plexus solaris) mittels Anästhetika',
                points: 300,
                simple_unit_rate: calculateRate(300),
                max_unit_rate: '?',
            },
        ],
    },
    {
        id: 'o',
        title: 'Strahlenmedizin/MRT',
        records: [
            {
                id: 'i',
                title: 'Strahlendiagnostik',
                records: [
                    {
                        id: 1,
                        title: 'Skelett',
                        records: [],
                    },
                    {
                        id: 2,
                        title: 'Hals- und Brustorgane',
                        records: [],
                    },
                    {
                        id: 3,
                        title: 'Bauch- und Verdauungsorgane',
                        records: [],
                    },
                    {
                        id: 4,
                        title: 'Spezialuntersuchungen',
                        records: [],
                    },
                    {
                        id: 5,
                        title: 'Angiographie',
                        records: [],
                    },
                    {
                        id: 6,
                        title: 'Interventionelle Maßnahmen',
                        records: [],
                    },
                    {
                        id: 7,
                        title: 'Computertomographie',
                        records: [
                            {
                                number: 5369,
                                title: 'Höchstwert für Leistungen nach den Nummern 5370 bis 5374',
                                points: 3000,
                                simple_unit_rate: calculateRate(3000),
                                max_unit_rate: '?',
                            },
                            {
                                number: 5370,
                                title: 'Computergesteuerte Tomographie im Kopfbereich gegebenenfalls einschließlich des kranio-zervikalen Übergangs',
                                points: 2000,
                                simple_unit_rate: calculateRate(2000),
                                max_unit_rate: '?',
                            },
                            {
                                number: 5371,
                                title: 'Computergesteuerte Tomographie im Hals- und/oder Thoraxbereich',
                                points: 2300,
                                simple_unit_rate: calculateRate(2300),
                                max_unit_rate: '?',
                            },
                            {
                                number: 5372,
                                title: 'Computergesteuerte Tomographie im Abdominalbereich',
                                points: 2600,
                                simple_unit_rate: calculateRate(2600),
                                max_unit_rate: '?',
                            },
                            {
                                number: 5373,
                                title: 'Computergesteuerte Tomographie des Skeletts (Wirbelsäule, Extremitäten oder Gelenke bzw. Gelenkpaare)',
                                points: 1900,
                                simple_unit_rate: calculateRate(1900),
                                max_unit_rate: '?',
                            },
                            {
                                number: 5374,
                                title: 'Computergesteuerte Tomographie der Zwischenwirbelräume im Bereich der Hals-, Brust- und/oder Lendenwirbelsäule gegebenenfalls einschließlich der Übergangsregionen',
                                points: 1900,
                                simple_unit_rate: calculateRate(1900),
                                max_unit_rate: '?',
                            },
                            {
                                number: 5375,
                                title: 'Computergesteuerte Tomographie der Aorta in ihrer gesamten Länge',
                                points: 2000,
                                simple_unit_rate: calculateRate(2000),
                                max_unit_rate: '?',
                            },
                            {
                                number: 5376,
                                title: 'Ergänzende computergesteuerte Tomographie(n) mit mindestens einer zusätzlichen Serie (z.B. bei Einsatz von Xenon, bei Einsatz der High-Resolution-Technik, bei zusätzlichen Kontrastmittelgaben) zusätzlich zu den Leistungen nach den Nummern 5370 bis 5375',
                                points: 500,
                                simple_unit_rate: calculateRate(500),
                                max_unit_rate: '?',
                            },
                            {
                                number: 5377,
                                title: 'Zuschlag für computergesteuerte Analyse einschließlich speziell nachfolgender 3D-Rekonstruktion',
                                points: 800,
                                simple_unit_rate: calculateRate(800),
                                max_unit_rate: '?',
                            },
                            {
                                number: 5378,
                                title: 'Computergesteuerte Tomographie zur Bestrahlungsplanung oder zu interventionellen Maßnahmen',
                                points: 1000,
                                simple_unit_rate: calculateRate(1000),
                                max_unit_rate: '?',
                            },
                            {
                                number: 5380,
                                title: 'Bestimmung des Mineralgehalts (Osteodensitometrie) von repräsentativen (auch mehreren) Skeletteilen mit quantitativer Computertomographie oder quantitativer digitaler Röntgentechnik',
                                points: 300,
                                simple_unit_rate: calculateRate(300),
                                max_unit_rate: '?',
                            },
                        ],
                    },
                ],
            },
            {
                id: 'ii',
                title: 'Nuklearmedizin',
                records: [],
            },
            {
                id: 'iii',
                title: 'Magnetresonanztomographie',
                records: [
                    {
                        number: 5700,
                        title: 'Magnetresonanztomographie im Bereich des Kopfes gegebenenfalls einschließlich des Halses , in zwei Projektionen, davon mindestens eine Projektion unter Einschluß T2-gewichteter Aufnahmen',
                        points: 4400,
                        simple_unit_rate: calculateRate(4400),
                        max_unit_rate: '?',
                    },
                    {
                        number: 5705,
                        title: 'Magnetresonanztomographie im Bereich der Wirbelsäule, in zwei Projektionen',
                        points: 4200,
                        simple_unit_rate: calculateRate(4200),
                        max_unit_rate: '?',
                    },
                    {
                        number: 5715,
                        title: 'Magnetresonanztomographie im Bereich des Thorax gegebenenfalls einschließlich des Halses, der Thoraxorgane und/oder der Aorta in ihrer gesamten Länge',
                        points: 4300,
                        simple_unit_rate: calculateRate(4300),
                        max_unit_rate: '?',
                    },
                    {
                        number: 5720,
                        title: 'Magnetresonanztomographie im Bereich des Abdomens und/oder des Beckens',
                        points: 4400,
                        simple_unit_rate: calculateRate(4400),
                        max_unit_rate: '?',
                    },
                    {
                        number: 5721,
                        title: 'Magnetresonanztomographie der Mamma(e)',
                        points: 4000,
                        simple_unit_rate: calculateRate(4000),
                        max_unit_rate: '?',
                    },
                    {
                        number: 5729,
                        title: 'Magnetresonanztomographie eines oder mehrerer Gelenke oder Abschnitte von Extremitäten',
                        points: 2400,
                        simple_unit_rate: calculateRate(2400),
                        max_unit_rate: '?',
                    },
                    {
                        number: 5730,
                        title: 'Magnetresonanztomographie einer oder mehrerer Extremität(en) mit Darstellung von mindestens zwei großen Gelenken einer Extremität',
                        points: 4000,
                        simple_unit_rate: calculateRate(4000),
                        max_unit_rate: '?',
                    },
                    {
                        number: 5731,
                        title: 'Ergänzende Serie(n) zu den Leistungen nach den Nummern 5700 bis 5730 (z.B. nach Kontrastmitteleinbringung, Darstellung von Arterien als MR-Angiographie)',
                        points: 1000,
                        simple_unit_rate: calculateRate(1000),
                        max_unit_rate: '?',
                    },
                    {
                        number: 5732,
                        title: 'Zuschlag zu den Leistungen nach den Nummern 5700 bis 5730 für Positionswechsel und/oder Spulenwechsel',
                        points: 1000,
                        simple_unit_rate: calculateRate(1000),
                        max_unit_rate: '?',
                    },
                    {
                        number: 5733,
                        title: 'Zuschlag für computergesteuerte Analyse (z. B. Kinetik, 3D-Rekonstruktion)',
                        points: 800,
                        simple_unit_rate: calculateRate(800),
                        max_unit_rate: '?',
                    },
                    {
                        number: 5735,
                        title: 'Höchstwert für Leistungen nach den Nummern 5700 bis 5730',
                        points: 6000,
                        simple_unit_rate: calculateRate(6000),
                        max_unit_rate: '?',
                    },
                ],
            },
            {
                id: 'iv',
                title: 'Strahlentherapie',
                records: [
                    {
                        id: 1,
                        title: 'Strahlenbehandlung dermatologischer Erkrankungen',
                        records: [],
                    },
                    {
                        id: 2,
                        title: 'Orthovolt- oder Hochvoltstrahlenbehandlung',
                        records: [],
                    },
                    {
                        id: 3,
                        title: 'Hochvoltstrahlenbehandlung bösartiger Erkrankungen (mindestens 1 MeV)',
                        records: [],
                    },
                    {
                        id: 4,
                        title: 'Brachytherapie mit umschlossenen Radionukliden',
                        records: [],
                    },
                    {
                        id: 5,
                        title: 'Besonders aufwendige Bestrahlungstechniken',
                        records: [],
                    },
                ],
            },
        ],
    },
    {
        id: 'p',
        title: 'Sektionsleistungen',
        records: [
            {
                number: 6000,
                title: 'Vollständige innere Leichenschau einschließlich Leichenschaubericht und pathologisch-anatomischer Diagnose',
                points: 1710,
                simple_unit_rate: calculateRate(1710),
                max_unit_rate: '?',
            },
            {
                number: 6001,
                title: 'Vollständige innere Leichenschau, die zusätzliche besonders zeitaufwendige oder umfangreiche ärztliche Verrichtungen erforderlich macht (z. B. ausgedehnte Untersuchung des Knochensystems oder des peripheren Gefäßsystems mit Präparierung und/oder Untersuchung von Organen bei fortschreitender Zersetzung mit bereits wesentlichen Fäulniserscheinungen) einschließlich Leichenschaubericht und pathologisch-anatomischer Diagnose',
                points: 2300,
                simple_unit_rate: calculateRate(2300),
                max_unit_rate: '?',
            },
            {
                number: 6002,
                title: 'Vollständige innere Leichenschau einer exhumierten Leiche am Ort der Exhumierung einschließlich Leichenschaubericht und pathologisch-anatomischer Diagnose',
                points: 3200,
                simple_unit_rate: calculateRate(3200),
                max_unit_rate: '?',
            },
            {
                number: 6003,
                title: 'Innere Leichenschau, die sich auf Teile einer Leiche und/oder auf einzelne Körperhöhlen beschränkt einschließlich Leichenschaubericht und pathologisch-anatomischer Diagnose',
                points: 739,
                simple_unit_rate: calculateRate(739),
                max_unit_rate: '?',
            },
            {
                number: 6010,
                title: 'Makroskopische neuropathologische Untersuchung des Zentralnervensystems (Gehirn, Rükkenmark) einer Leiche einschließlich Organschaubericht und pathologisch-anatomischer Diagnose',
                points: 400,
                simple_unit_rate: calculateRate(400),
                max_unit_rate: '?',
            },
            {
                number: 6015,
                title: 'Mikroskopische Untersuchung von Organen (Haut, Muskel, Leber, Niere, Herz, Milz, Lunge) nach innerer Leichenschau einschließlich Beurteilung des Befundes, je untersuchtes Organ',
                points: 242,
                simple_unit_rate: calculateRate(242),
                max_unit_rate: '?',
            },
            {
                number: 6016,
                title: 'Mikroskopische Untersuchung eines Knochens nach innerer Leichenschau einschließlich Beurteilung des Befundes , je Knochen',
                points: 300,
                simple_unit_rate: calculateRate(300),
                max_unit_rate: '?',
            },
            {
                number: 6017,
                title: 'Mikroskopische Untersuchung von vier oder mehr Knochen nach innerer Leichenschau einschließlich Beurteilung des Befundes',
                points: 1045,
                simple_unit_rate: calculateRate(1045),
                max_unit_rate: '?',
            },
            {
                number: 6018,
                title: 'Mikroskopische Untersuchung von Nerven oder Rückenmark oder Gehirn nach innerer Leichenschau einschließlich des Befundes',
                points: 300,
                simple_unit_rate: calculateRate(300),
                max_unit_rate: '?',
            },
        ],
    },
];

export default data;
